### ISSUE TITLE
Me desbloqueia!

### ISSUE THREAD

**Issue by mateusbertan** [Kovanight/Kovanight#1]
Por favor, me desbloqueia no Telegram.

Precisamos conversar.

**Comment by Kovanight** [comment]
@mateusbertan para de me perseguir, tá pior que o diabo e não é pra ficar abrindo Issue.

**Comment by mateusbertan** [comment]
Eu só abri essa issues para pedir que tu me desbloqueie. Não estou te perseguindo, eu só achei esse lugar para conversar contigo (todos os outros lugares tu me bloqueou).

Eu só quero saber porque tu não quer mais falar comigo, se eu fiz algo ou se tá acontecendo algo.

Se tu não quer falar comigo eu respeito, mas não precisa me bloquear e simplesmente parar de falar comigo de uma hora para a outra.

Por favor, responde.

**Comment by Kovanight** [comment]
não vou desbloquear. ( ponto final ) e me recuso a responder a sua pessoa novamente.
